"""empty message

Revision ID: 40bef8852b78
Revises: eb19730c6b19
Create Date: 2023-01-05 22:08:33.944178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40bef8852b78'
down_revision = 'eb19730c6b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_ordered',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size_range', mysql.LONGTEXT(), nullable=False),
    sa.Column('colours', mysql.LONGTEXT(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('variation', mysql.LONGTEXT(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('wholesale_sales',
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('shop_no', sa.String(length=10), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wholesale_sales')
    op.drop_table('stock_ordered')
    # ### end Alembic commands ###
