"""add index column in stock ordered and logs

Revision ID: 496e90d5b5a5
Revises: 6d9952f2d3f2
Create Date: 2023-01-10 12:36:55.384206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496e90d5b5a5'
down_revision = '6d9952f2d3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ordered', sa.Column('index', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stock_ordered_index'), 'stock_ordered', ['index'], unique=True)
    op.add_column('stocklogs', sa.Column('index', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stocklogs_index'), 'stocklogs', ['index'], unique=True)
    # op.drop_index('ix_wholesale_sales_index', table_name='wholesale_sales')
    # op.create_index(op.f('ix_wholesale_sales_index'), 'wholesale_sales', ['index'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wholesale_sales_index'), table_name='wholesale_sales')
    op.create_index('ix_wholesale_sales_index', 'wholesale_sales', ['index'], unique=False)
    op.drop_index(op.f('ix_stocklogs_index'), table_name='stocklogs')
    op.drop_column('stocklogs', 'index')
    op.drop_index(op.f('ix_stock_ordered_index'), table_name='stock_ordered')
    op.drop_column('stock_ordered', 'index')
    # ### end Alembic commands ###
