"""create schemas

Revision ID: 52ac3d5b0aed
Revises: 
Create Date: 2023-01-20 15:26:34.869456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52ac3d5b0aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_sales',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('shop_no', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_retail_sales_index'), 'retail_sales', ['index'], unique=True)
    op.create_table('stock_available',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size_range', mysql.LONGTEXT(), nullable=False),
    sa.Column('colours', mysql.LONGTEXT(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('variation', mysql.LONGTEXT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_ordered',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size_range', mysql.LONGTEXT(), nullable=False),
    sa.Column('colours', mysql.LONGTEXT(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('variation', mysql.LONGTEXT(), nullable=False),
    sa.Column('order_price', sa.Integer(), nullable=False),
    sa.Column('shipping_co', sa.String(length=100), nullable=True),
    sa.Column('comments', mysql.LONGTEXT(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_stock_ordered_index'), 'stock_ordered', ['index'], unique=True)
    op.create_table('stocklogs',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size_range', mysql.LONGTEXT(), nullable=False),
    sa.Column('colours', mysql.LONGTEXT(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('variation', mysql.LONGTEXT(), nullable=False),
    sa.Column('Shipper_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('depletion_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_stocklogs_index'), 'stocklogs', ['index'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('Fullname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('rights', sa.String(length=10), nullable=False),
    sa.Column('shop', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wholesale_sales',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('shop_no', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_wholesale_sales_index'), 'wholesale_sales', ['index'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wholesale_sales_index'), table_name='wholesale_sales')
    op.drop_table('wholesale_sales')
    op.drop_table('user')
    op.drop_index(op.f('ix_stocklogs_index'), table_name='stocklogs')
    op.drop_table('stocklogs')
    op.drop_index(op.f('ix_stock_ordered_index'), table_name='stock_ordered')
    op.drop_table('stock_ordered')
    op.drop_table('stock_available')
    op.drop_index(op.f('ix_retail_sales_index'), table_name='retail_sales')
    op.drop_table('retail_sales')
    # ### end Alembic commands ###
