"""added depletion date to stock logs

Revision ID: 6d9952f2d3f2
Revises: 5e638adca7b7
Create Date: 2023-01-10 10:09:15.086859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9952f2d3f2'
down_revision = '5e638adca7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocklogs', sa.Column('depletion_date', sa.Date(), nullable=True))
    # op.drop_index('index_UNIQUE', table_name='wholesale_sales')
    # op.drop_index(op.f('ix_wholesale_sales_index'), table_name='wholesale_sales')
    # op.create_index(op.f('ix_wholesale_sales_index'), 'wholesale_sales', ['index'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wholesale_sales_index'), table_name='wholesale_sales')
    op.create_index('ix_wholesale_sales_index', 'wholesale_sales', ['index'], unique=False)
    op.create_index('index_UNIQUE', 'wholesale_sales', ['index'], unique=False)
    op.drop_column('stocklogs', 'depletion_date')
    # ### end Alembic commands ###
