"""added status column to wholesale sales

Revision ID: 86d4e3e3b030
Revises: 40bef8852b78
Create Date: 2023-01-06 09:07:15.733680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d4e3e3b030'
down_revision = '40bef8852b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wholesale_sales', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('wholesale_sales', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wholesale_sales', 'date')
    op.drop_column('wholesale_sales', 'status')
    # ### end Alembic commands ###
