"""empty message

Revision ID: c506fd4d5279
Revises: c3688aa2bc5c
Create Date: 2022-10-01 05:57:42.622539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c506fd4d5279'
down_revision = 'c3688aa2bc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocklogs', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocklogs', 'date')
    # ### end Alembic commands ###
