"""create sales variation column, fix error to longtext

Revision ID: eb19730c6b19
Revises: 025dd432613f
Create Date: 2022-12-31 00:58:22.666623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb19730c6b19'
down_revision = '025dd432613f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_logs', sa.Column('sold_data', mysql.LONGTEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_logs', 'sold_data')
    # ### end Alembic commands ###
