"""empty message

Revision ID: fa94a165e12e
Revises: 52ac3d5b0aed
Create Date: 2023-01-26 20:50:59.312380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa94a165e12e'
down_revision = '52ac3d5b0aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wholesale_sales', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wholesale_sales', 'price')
    # ### end Alembic commands ###
