# Generated by Django 5.2.6 on 2025-09-22 21:06

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_and_Debit_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_name', models.CharField(max_length=50)),
                ('debt', models.IntegerField()),
                ('Amount_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('sizes', models.JSONField()),
                ('colours', models.JSONField()),
                ('product_variation', models.JSONField()),
                ('amount', models.IntegerField()),
                ('order_amount', models.IntegerField(null=True)),
                ('Arrival_date', models.DateField(default=datetime.date.today)),
                ('depletion_date', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Order_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_range', models.JSONField()),
                ('colours', models.JSONField()),
                ('amount', models.IntegerField()),
                ('variation', models.JSONField()),
                ('order_price', models.IntegerField(null=True)),
                ('shipping_co', models.CharField(max_length=100, null=True)),
                ('comments', models.TextField(null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('proposed_arrival', models.DateField(null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('arrived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Retail_Sales_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('buyer_name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('balanced_out', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('Date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('Last_visit', models.DateTimeField(default=datetime.datetime.today)),
                ('migrated', models.BooleanField(default=False)),
                ('shop_number', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Products_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Colour', models.CharField(max_length=20)),
                ('Size', models.CharField(max_length=7)),
                ('Price', models.IntegerField(null=True)),
                ('Amount', models.IntegerField()),
                ('Batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='utils.products_logs')),
            ],
        ),
        migrations.AddField(
            model_name='products_logs',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.products_order_logs'),
        ),
        migrations.CreateModel(
            name='Wholesale_Sales_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField()),
                ('Batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='utils.products_logs')),
            ],
        ),
    ]
