# Generated by Django 4.1.6 on 2023-02-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('colour', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('paid', models.BooleanField(default=False)),
                ('buyer', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime(2023, 2, 13, 15, 36, 26, 545460))),
            ],
        ),
    ]
