# Generated by Django 4.1.6 on 2023-02-13 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_retailsales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsales',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
