# Generated by Django 4.1.6 on 2023-02-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_retailsales_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableStock',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('size_range', models.TextField()),
                ('colours', models.TextField()),
                ('amount', models.IntegerField()),
                ('variation', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('colour', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_range', models.TextField()),
                ('colours', models.TextField()),
                ('amount', models.IntegerField()),
                ('variation', models.TextField()),
                ('order_price', models.IntegerField()),
                ('shipping_co', models.CharField(max_length=100, null=True)),
                ('comments', models.TextField(null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('arrival_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_range', models.TextField()),
                ('colours', models.TextField()),
                ('amount', models.IntegerField()),
                ('variation', models.TextField()),
                ('Shipper_name', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('depletion_date', models.DateField(default=None)),
            ],
        ),
    ]
