# Generated by Django 4.1.6 on 2023-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_availablestock_localsales_ordered_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Fullname', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('rights', models.CharField(default='attendant', max_length=15)),
                ('shop', models.CharField(max_length=20)),
            ],
        ),
    ]
