# Generated by Django 4.1.6 on 2023-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='depletion_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
