# Generated by Django 4.1.6 on 2023-02-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_ordered_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsales',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
