# Generated by Django 4.1.6 on 2023-03-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsales',
            name='balanced_out',
            field=models.BooleanField(default=False),
        ),
    ]
