# Generated by Django 4.1.6 on 2023-04-10 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_retailsales_balanced_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Available',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Colour', models.CharField(max_length=20)),
                ('Size', models.CharField(max_length=7)),
                ('Price', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('shipper_name', models.CharField(max_length=255, null=True)),
                ('sizes', models.JSONField()),
                ('colours', models.JSONField()),
                ('product_variation', models.JSONField()),
                ('amount', models.IntegerField()),
                ('Arrival_date', models.DateField(default=datetime.date.today)),
                ('depletion_date', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Order_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_range', models.JSONField()),
                ('colours', models.JSONField()),
                ('amount', models.IntegerField()),
                ('variation', models.JSONField()),
                ('order_price', models.IntegerField()),
                ('shipping_co', models.CharField(max_length=100, null=True)),
                ('comments', models.TextField(null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('proposed_arrival', models.DateField(null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('arrived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wholesale_Sales_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='products_logs',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.products_order_logs'),
        ),
        migrations.AddField(
            model_name='products_available',
            name='Batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.products_logs'),
        ),
    ]
