# Generated by Django 4.1.6 on 2023-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_products_available_products_logs_products_order_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_order_logs',
            name='order_price',
            field=models.IntegerField(null=True),
        ),
    ]
