# Generated by Django 4.1.6 on 2023-04-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_remove_products_logs_shipper_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale_sales_logs',
            name='Batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utils.products_logs'),
        ),
    ]
