# Generated by Django 4.1.6 on 2023-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_wholesale_sales_logs_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_available',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
