# Generated by Django 4.1.6 on 2023-04-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_alter_products_available_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products_Available',
        ),
    ]
