# Generated by Django 4.1.6 on 2023-04-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_delete_products_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Colour', models.CharField(max_length=20)),
                ('Size', models.CharField(max_length=7)),
                ('Price', models.IntegerField(null=True)),
                ('Amount', models.IntegerField()),
                ('Batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.products_logs')),
            ],
        ),
    ]
