# Generated by Django 4.1.6 on 2023-04-20 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_products_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_Sales_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('buyer_name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('balanced_out', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
