# Generated by Django 4.1.6 on 2023-04-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_retail_sales_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_available',
            name='Batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='utils.products_logs'),
        ),
        migrations.AlterField(
            model_name='wholesale_sales_logs',
            name='Batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='utils.products_logs'),
        ),
    ]
