# Generated by Django 4.1.6 on 2023-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_credit_and_debit_management_delete_availablestock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_logs',
            name='order_amount',
            field=models.IntegerField(null=True),
        ),
    ]
